server:
  port: 9091

spring:
  datasource:
    url: jdbc:h2:mem:person-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      path: /db-console
  application:
    name: person-application
  profiles:
    include: swagger-eureka

eureka:
  instance:
    appname: person-application
    metadata-map:
      swagger_url: http://localhost:9091

springfox:
  documentation:
    swagger:
      v2:
        path: /v2/api-docs.json